// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3g36EX6y5D4MZk5BxkYxnpiPhAC2JOC8',
    appId: '1:84177981190:web:ae200fadd1523ea75bd887',
    messagingSenderId: '84177981190',
    projectId: 'exam-reactjs',
    authDomain: 'exam-reactjs.firebaseapp.com',
    storageBucket: 'exam-reactjs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_gvHZ9O1vBx5L-TH3EUJa0L-QXDXrqbI',
    appId: '1:84177981190:android:b5f1da00764ba7645bd887',
    messagingSenderId: '84177981190',
    projectId: 'exam-reactjs',
    storageBucket: 'exam-reactjs.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYyqdUXRqcy1TEQcRyZbRdI1CADVF3qTQ',
    appId: '1:84177981190:ios:bf99f807bb845ad55bd887',
    messagingSenderId: '84177981190',
    projectId: 'exam-reactjs',
    storageBucket: 'exam-reactjs.appspot.com',
    iosClientId: '84177981190-ltnq64obt1rgb47jp2egdcp842b71ktc.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorApp.RunnerTests',
  );
}
